name: Log Time Job

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  log_time:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout repository

      - name: Run logging script
        run: |
          chmod +x log_time.sh  # Make the script executable
          ./log_time.sh  # Run the logging script

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main  # Fetch latest changes to avoid conflicts
          git add log.txt  # Stage log.txt for commit
          git commit -m "Update log file with new timestamp" || echo "No changes to commit"  # Commit if there are changes
          git push origin main  # Push changes to the repository
